BookStore/urls.py
# book_platform/book_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'BookStore'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('listings.urls')),
    path('chat/', include('chat.urls')),
    path('reviews/', include('reviews.urls')),
    path('complaints/', include('complaints.urls')),
    path('wishlist/', include('wishlist.urls')),
]
urlpatterns +=     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('start/<int:listing_id>/', views.start_chat, name='start_chat'),
    path('list/', views.chat_list, name='chat_list'),
    path('<int:chat_id>/', views.chat_detail, name='chat_detail'),
    path('notifications/', views.notifications, name='notifications'),
]

complaints/urls.py
from django.urls import path
from . import views

app_name = 'complaints'

urlpatterns = [
    path('submit/', views.submit_complaint, name='submit_complaint'),
]

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listing_list, name='list'),
    path('create/', views.create_listing, name='create'),
    path('<int:pk>/', views.listing_detail, name='detail'),
    path('<int:pk>/edit/', views.edit_listing, name='edit'),
    path('<int:pk>/delete/', views.delete_listing, name='delete'),
]

users/urls.py
# book_platform/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('logout/', auth_views.LogoutView.as_view(next_page='listings:listing_list'), name='logout'),
]

BookStore/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError

# Валидатор для ограничения размера изображения
def validate_image_size(value):
    max_size = 3 * 1024 * 1024  # 3 МБ в байтах
    if value.size > max_size:
        raise ValidationError('Размер изображения не должен превышать 3 МБ.')

# Модель City (Города)
class City(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'City'
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.name

# Модель Category (Категории)
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'Category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

# Модель Tag (Теги)
class Tag(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'Tag'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name

# Модель Role (Роли)
class Role(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        db_table = 'Role'
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'

    def __str__(self):
        return self.name

# Модель User (Пользователи)
class User(AbstractUser):
    first_name = models.CharField(max_length=30)  # Имя
    last_name = models.CharField(max_length=30)   # Фамилия
    patronymic = models.CharField(max_length=30, null=True, blank=True)  # Отчество
    phone_number = models.CharField(max_length=15, null=True, blank=True)  # Номер телефона
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, validators=[validate_image_size])  # Аватар
    description = models.TextField(null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(auto_now_add=True)
    is_banned = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    class Meta:
        db_table = 'User'
        indexes = [models.Index(fields=['email'])]
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

    @property
    def rating(self):
        reviews = self.reviews_received.all()
        if reviews.exists():
            total = sum(review.rating for review in reviews)
            return round(total / reviews.count(), 2)
        return None

# Модель UserRole (Роли пользователей)
class UserRole(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)

    class Meta:
        db_table = 'UserRole'
        unique_together = ('user', 'role')
        verbose_name = 'Роль пользователя'
        verbose_name_plural = 'Роли пользователей'

    def __str__(self):
        return f"{self.user.username} - {self.role.name}"

# Модель Listing (Объявления)
class Listing(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=100)
    series = models.CharField(max_length=100, null=True, blank=True)
    number_of_pages = models.IntegerField(null=True, blank=True)
    isbn = models.CharField(max_length=20, unique=True, null=True, blank=True)
    dimensions = models.CharField(max_length=50, null=True, blank=True)
    publisher = models.CharField(max_length=100, null=True, blank=True)
    cover_type = models.CharField(max_length=50, null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    illustrations_type = models.CharField(max_length=50, null=True, blank=True)
    language = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    is_exchange = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, through='ListingTags')
    CONDITION_CHOICES = [
        ('new', 'Новое'),
        ('like_new', 'Почти новое'),
        ('good', 'Хорошее'),
        ('fair', 'Посредственное'),
        ('poor', 'Плохое'),
    ]
    condition = models.CharField(max_length=20, choices=CONDITION_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    MODERATION_CHOICES = [
        ('pending', 'На модерации'),
        ('approved', 'Подтверждено'),
        ('rejected', 'Отказано'),
    ]
    moderation_status = models.CharField(max_length=20, choices=MODERATION_CHOICES)
    STATUS_CHOICES = [
        ('active', 'Активное'),
        ('sold', 'Продано'),
        ('exchanged', 'Exchanged'),
        ('deleted', 'Удалено'),

    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    exchange_conditions = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'Listing'
        indexes = [models.Index(fields=['seller']), models.Index(fields=['status'])]
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

    def __str__(self):
        return f"{self.title} by {self.author}"

# Модель Listing_Tags (Теги объявлений)
class ListingTags(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Listing_Tags'
        unique_together = ('listing', 'tag')
        verbose_name = 'Тег объявления'
        verbose_name_plural = 'Теги объявлений'

    def __str__(self):
        return f"{self.listing.title} - {self.tag.name}"

# Модель Image (Изображения)
class Image(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='listing_images/', null=True, blank=True, validators=[validate_image_size])

    class Meta:
        db_table = 'ListingImage'
        verbose_name = 'Изображение объявления'
        verbose_name_plural = 'Изображения объявлений'

    def __str__(self):
        return f"Image for {self.listing.title}"

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    author = models.CharField(max_length=100, null=True, blank=True)
    language = models.CharField(max_length=50, null=True, blank=True)
    MIN_CONDITION_CHOICES = [
        ('new', 'Новое'),
        ('like_new', 'Почти новое'),
        ('good', 'Хорошее'),
        ('fair', 'Посредственное'),
        ('poor', 'Плохое'),
    ]
    min_condition = models.CharField(max_length=20, choices=MIN_CONDITION_CHOICES, null=True, blank=True)
    price_min = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    price_max = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    series = models.CharField(max_length=100, null=True, blank=True)
    number_of_pages = models.IntegerField(null=True, blank=True)
    isbn = models.CharField(max_length=20, null=True, blank=True)
    dimensions = models.CharField(max_length=50, null=True, blank=True)
    publisher = models.CharField(max_length=100, null=True, blank=True)
    cover_type = models.CharField(max_length=50, null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    illustrations_type = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_exchange = models.BooleanField(null=True, blank=True)
    exchange_conditions = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'Wishlist'
        indexes = [models.Index(fields=['user'])]
        verbose_name = 'Список желаемого'
        verbose_name_plural = 'Списки желаемого'

    def __str__(self):
        return f"{self.user.username}'s wishlist"

# Модель Wishlist_Categories (Категории желаемого)
class WishlistCategories(models.Model):
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_links')

    class Meta:
        db_table = 'Wishlist_Categories'
        unique_together = ('wishlist', 'category')
        verbose_name = 'Категория желаемого'
        verbose_name_plural = 'Категории желаемого'

    def __str__(self):
        return f"{self.wishlist} - {self.category.name}"

# Модель Wishlist_Tags (Теги желаемого)
class WishlistTags(models.Model):
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE, related_name='tag_links')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Wishlist_Tags'
        unique_together = ('wishlist', 'tag')
        verbose_name = 'Тег желаемого'
        verbose_name_plural = 'Теги желаемого'

    def __str__(self):
        return f"{self.wishlist} - {self.tag.name}"

# Модель Chat (Чаты)
class Chat(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Chat'
        indexes = [models.Index(fields=['listing'])]
        verbose_name = 'Чат'
        verbose_name_plural = 'Чаты'

    def __str__(self):
        return f"Chat {self.id}"

# Модель ChatParticipant (Участники чата)
class ChatParticipant(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from BookStore.models import User, City, Wishlist
class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше имя'}), required=True, label="Имя")
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите вашу фамилию'}), required=True, label="Фамилия")
    patronymic = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваше отчество'}), required=False, label="Отчество")
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш номер телефона'}), required=False, label="Номер телефона")
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите вашу почту'}), required=True, label="Почта")
    city = forms.ModelChoiceField(queryset=City.objects.all(), widget=forms.Select(attrs={'class': 'form-select'}), required=True, label="Город")
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш логин'}), required=True, label="Логин")
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}), label="Пароль")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}), label="Подтверждение пароля")

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'city', 'username', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Этот email уже зарегистрирован.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Этот логин уже занят.")
        return username


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'patronymic', 'phone_number', 'email', 'city', 'avatar', 'description']
        widgets = {'avatar': forms.FileInput()}

users/views.py
# users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from .forms import RegistrationForm, ProfileForm
from BookStore.models import Listing, Review, Complaint, User

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # send_mail(
            #     'Добро пожаловать!',
            #     'Спасибо за регистрацию на нашей платформе!',
            #     settings.DEFAULT_FROM_EMAIL,
            #     [user.email],
            #     fail_silently=False,
            # )
            return redirect('users:profile')  # Используем пространство имен
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('users:profile')  # Используем пространство имен
        else:
            return render(request, 'users/login.html', {'error': 'Неверный логин или пароль'})
    return render(request, 'users/login.html')


#TODO: сделать так, чтобы другие пользователи не видели скрытые обхявления (не обработанные)
@login_required
def profile(request, user_id=None):
    if user_id:
        user = get_object_or_404(User, id=user_id)
    else:
        user = request.user
    listings = Listing.objects.filter(seller=user)
    reviews = Review.objects.filter(to_user=user)
    complaints = Complaint.objects.filter(target_user=user)
    context = {
        'user': user,
        'listings': listings,
        'reviews': reviews,
        'complaints': complaints,
    }
    return render(request, 'users/profile.html', context)

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')  # Используем пространство имен
    else:
        form = ProfileForm(instance=request.user)
    return render(request, 'users/edit_profile.html', {'form': form})

users/templates/users/edit_profile.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <h2>Редактировать профиль</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{% url 'users:profile' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Вход{% endblock %}
{% block content %}
<div class="card mx-auto" style="max-width: 400px; margin-top: 50px;">
    <div class="card-header">
        <h2>Вход</h2>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username" class="form-label">Логин</label>
                <input type="text" name="username" class="form-control" id="id_username" required>
            </div>
            <div class="mb-3">
                <label for="id_password" class="form-label">Пароль</label>
                <input type="password" name="password" class="form-control" id="id_password" required>
            </div>
            {% if error %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endif %}
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
        <p class="mt-3">Забыли пароль? <a href="#">Восстановить</a>.</p>
        <p class="mt-1">Нет аккаунта? <a href="{% url 'users:register' %}">Зарегистрироваться</a>.</p>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Профиль{% endblock %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Информация о профиле слева -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body d-flex align-items-center">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" alt="Аватар" class="rounded-circle me-3" style="width: 100px; height: 100px; object-fit: cover;">
                    {% else %}
                        <div class="rounded-circle me-3 bg-secondary" style="width: 100px; height: 100px;"></div>
                    {% endif %}
                    <div>
                        <h3 class="card-title">{{ user.first_name }}</h3>
                        <p><strong>Имя:</strong> {{ user.first_name }} {{ user.last_name }} {% if user.patronymic %}{{ user.patronymic }}{% endif %}</p>
                    </div>

                </div>
                <div class="card-body">
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    {% if user.phone_number %}
                        <p><strong>Телефон:</strong> {{ user.phone_number }}</p>
                    {% endif %}
                    <p><strong>Город:</strong> {{ user.city }}</p>
                    {% if user.description %}
                        <p><strong>Описание:</strong> {{ user.description }}</p>
                    {% endif %}
                    {% if user.rating %}
                        <p><strong>Рейтинг:</strong> {{ user.rating|default:"Не оценен"  }}</p>
                    {% endif %}

                </div>
                {% if user == request.user %}
                           <a href="{% url 'users:edit_profile' %}" class="btn btn-primary mt-3">Редактировать профиль</a>
                    {% endif %}
                {% if user != request.user %}
                        <a href="{% url 'complaints:submit_complaint' %}?target_user_id={{ user.id }}" class="btn btn-danger mt-2">Пожаловаться</a>
                    {% endif %}
            </div>
        </div>


        <!-- Объявления справа -->
        <div class="col-md-8">
            <h3>Объявления</h3>
            {% for listing in listings %}

                <div class="card mb-3 {% if listing.status in 'deleted,sold,exchanged' %}bg-light text-muted{% elif listing.moderation_status == 'pending' %}bg-warning{% endif %}">
                    <div class="card-body d-flex">
                        <!-- Изображение объявления -->
                        <div class="p-2">
                            {% if listing.images.all %}
                                <img src="{{ listing.images.first.image.url }}" alt="{{ listing.title }}" class="rounded" style="width: 150px; height: 150px; object-fit: cover;">
                            {% else %}
                                <div class="bg-secondary rounded" style="width: 150px; height: 150px; display: flex; align-items: center; justify-content: center; color: white;">Нет изображения</div>
                            {% endif %}
                        </div>
                        <!-- Информация об объявлении -->
                        <div class="flex-grow-1">
                            <h5 class="card-title">
                                <a href="{% url 'listings:detail' listing.pk %}" class="{% if listing.status in 'deleted,sold,exchanged' %}text-muted{% endif %}">{{ listing.title }}</a>
                            </h5>
                            <p class="card-text">Автор: {{ listing.author }}</p>
                            <p class="card-text">Категория: {{ listing.category }}</p>
                            <p class="card-text">Цена: {{ listing.price|default:"Обмен" }}</p>
                            <p class="card-text">Статус: {{ listing.get_status_display }}</p>
                            <p class="card-text">Модерация: {{ listing.get_moderation_status_display }}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>У пользователя нет объявлений.</p>
            {% endfor %}
        </div>
    </div>
<div class="row mt-4">
        <div class="col-12">
            <h3>Отзывы</h3>
            {% for review in reviews %}
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <!-- Слева: краткая сводка об объявлении -->
                            <div class="col-md-6">
                                {% if review.listing %}
                                    <div class="card d-flex flex-row">
                                        <div class="p-2">
                                            {% if review.listing.images.all %}
                                                <img src="{{ review.listing.images.first.image.url }}" alt="{{ review.listing.title }}" class="rounded" style="width: 150px; height: 150px; object-fit: cover;">
                                            {% else %}
                                                <div class="bg-secondary rounded" style="width: 150px; height: 150px; display: flex; align-items: center; justify-content: center; color: white;">Нет изображения</div>
                                            {% endif %}
                                        </div>
                                        <div class="card-body">
                                            <h5 class="card-title">{{ review.listing.title }}</h5>
                                            <p class="card-text mb-1"><strong>Автор:</strong> {{ review.listing.author }}</p>
                                            <p class="card-text mb-1"><strong>Категория:</strong> {{ review.listing.category.name }}</p>
                                            <p class="card-text mb-1"><strong>Цена:</strong> {{ review.listing.price|default:"Обмен" }}</p>
                                            <div class="mt-2">
                                                <strong>Теги:</strong>
                                                {% for tag in review.listing.tags.all|slice:":3" %}
                                                    <span class="badge bg-secondary">{{ tag.name }}</span>
                                                {% endfor %}
                                                {% if review.listing.tags.count > 3 %}
                                                    <span>...</span>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                {% else %}
                                    <p>Объявление удалено</p>
                                {% endif %}
                            </div>
                            <!-- Справа: информация об отзыве -->
                            <div class="col-md-6">
                                <p><strong>От:</strong> {{ review.from_user.first_name }} {{ review.from_user.last_name }} {% if review.from_user.patronymic %}{{ review.from_user.patronymic }}{% endif %}</p>
                                <p><strong>Рейтинг:</strong> {{ review.rating }} / 5</p>
                                <p><strong>Текст:</strong> {{ review.text|default:"Нет текста" }}</p>
                                <p><small>Дата: {{ review.created_at|date:"d.m.Y H:i" }}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>Нет отзывов.</p>
            {% endfor %}

            <h3>Жалобы</h3>
            {% for complaint in complaints %}
                <div class="card mb-3">
                    <div class="card-body ">
                        <p><strong>От:</strong> {{ complaint.reporter.first_name }} {{ complaint.reporter.last_name }} {% if complaint.reporter.patronymic %}{{ complaint.reporter.patronymic }}{% endif %}</p>
                        <p><strong>Причина:</strong> {{ complaint.reason }}</p>
                        <p><strong>Сообщение:</strong> {{ complaint.message }}</p>
                        <p><small>Дата: {{ complaint.created_at|date:"d.m.Y H:i" }}</small></p>
                    </div>
                </div>
            {% empty %}
                <p>Нет жалоб.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}